baseURL = "https://www.bmpi.dev"
title = "Build My Passive Income"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

enableRobotsTXT = true
canonifyURLs = true

enableGitInfo = true
enableEmoji = true

paginate = 9999

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false
pluralizelisttitles = false

FootnoteReturnLinkContents = "â†‘"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "Shidi"
    info1 = "ğŸ“š"
    info1Tooltip = "Lifelong Learner"
    info2 = "ğŸ‘¨â€ğŸ’»"
    info2Tooltip = "Full-Stack Developer"
    info3 = "ğŸ’´"
    info3Tooltip = "ETF Trader"
    description = "Study + Craft + Invest = BMPI.dev"
    keywords = "life,dev,trade,passive income,money,developer,Self-management,IT technology,investment transactions"
    avatarurl = "images/cat.png"
    logoImg = "images/cat.png"
    header = "BMPI.dev"


    github = "nszaaa3"
    favicon_32 = "images/f3/favicon-32x32.png"
    favicon_16 = "images/f3/favicon-16x16.png"

    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    series = true

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js", "/js/flying-pages.min.js", "/js/custom.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = true
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-1886683614725279"
    googleAnalytics = "UA-154678195-1"

    # OG
    og_image = "images/bg2.png"

# Comments on github issue
[params.utteranc]
    repo = "bmpi-dev/bmpi.dev"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/nszaaa3"

[[params.social]]
    name = "Newsletter"
    icon = "fas fa-envelope"
    weight = 6
    url = "https://tinyletter.com/i365"

[languages]

    [languages.zh-cn]
        languagename = "Chinese"
        title = "Unnamed"

        [languages.zh-cn.params]
            author = "å°å…‹è¿ª"
            info1 = "ğŸ“š"
            info1Tooltip = "ç»ˆèº«å­¦ä¹ /è®¤çŸ¥æ æ†"
            info2 = "ğŸ‘¨â€ğŸ’»"
            info2Tooltip = "å…¨æ ˆæŠ€æœ¯/æ—¶é—´æ æ†"
            info3 = "ğŸ’´"
            info3Tooltip = "æŠ•èµ„ç†è´¢/è´¢åŠ¡æ æ†"
            description = "é€šè¿‡å­¦ä¹ ï¼ˆGTDã€æ—¶é—´ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€å†™ä½œã€è´¢åŠ¡ç®¡ç†ï¼‰ã€æŠ€æœ¯åˆ›é€ ï¼ˆå‰ç«¯ã€åç«¯ã€ç§»åŠ¨ç«¯ã€DevOpsï¼‰ã€æŠ•èµ„ï¼ˆæŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ï¼‰ã€ç½‘èµšé¡¹ç›®ï¼ˆSEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ï¼‰æ¥å»ºç«‹è¢«åŠ¨æ”¶å…¥"
            keywords = "è‡ªæˆ‘æå‡ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€æ‘„å½±ã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€æŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ã€SEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ã€è¢«åŠ¨æ”¶å…¥ã€ç½‘èµš"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]

            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 2
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "å­¦ä¹ "
                weight = 3
                url  = "/self/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ€æœ¯"
                weight = 4
                url  = "/dev/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ•èµ„"
                weight = 5
                url  = "/money/"
            [[languages.zh-cn.menu.main]]
                name = "ä¸ªäººé¡¹ç›®"
                weight = 6
                url  = "/project/"
            [[languages.zh-cn.menu.main]]
                name = "é•¿æœŸç›®æ ‡"
                weight = 7
                url  = "/goal/"
